#!/opt/syschecks/venv/bin/python3
import sys
from os.path import exists

if exists("/opt/syschecks/") and exists("/opt/syschecks/syschecks"):
    sys.path.insert(1, "/opt/syschecks/")
else:
    print("SysChecks is not installed properly!", file=sys.stderr)
    sys.exit(1)

from main import app

app()
